<?php
session_start();

// Use ONLY the combined database connection
include "db.php";  
include 'header.php';

// Load menu items
$menu = [];
$sql = "SELECT item_id, name AS item_name, price FROM menu_items";
$result = $conn->query($sql);

if (!$result) {
    die("SQL ERROR: " . $conn->error);
}

while ($row = $result->fetch_assoc()) {
    $menu[] = $row;
}

require_once "auth.php";    
require_once "cart_logic.php";

// ---------- FIXED TOTAL CALCULATION ----------
$total_display = 0;

if (!empty($_SESSION['cart'])) {
    foreach ($_SESSION['cart'] as $id => $qty) {

        $item_price = null;

        // 1️⃣ Check menu_items
        foreach ($menu as $m) {
            if ($m['item_id'] == $id) {
                $item_price = $m['price'];
                break;
            }
        }

        // 2️⃣ Check specials
        if ($item_price === null) {
            foreach ($specials as $s) {
                if ($s['item_id'] == $id) {
                    $item_price = $s['price'];
                    break;
                }
            }
        }

        // Add to total
        if ($item_price !== null) {
            $total_display += ($item_price * $qty);
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basilico – Order Online</title>
    <link rel="stylesheet" href="orderonline.css">
</head>
<body>

<main>

    <!-- Combined Error / success messages -->
    <div class="messages">
        <!-- Display flash messages from other pages (like addtocart.php) -->
        <?php
        if (isset($_SESSION['flash_success'])) {
            echo '<div class="success">' . htmlspecialchars($_SESSION['flash_success']) . '</div>';
            unset($_SESSION['flash_success']);
        }
        if (isset($_SESSION['flash_error'])) {
            echo '<div class="error">' . htmlspecialchars($_SESSION['flash_error']) . '</div>';
            unset($_SESSION['flash_error']);
        }
        ?>

        <!-- Display messages generated by cart_logic.php -->
        <?php if (isset($errors) && !empty($errors)): ?>
            <?php foreach ($errors as $e): ?>
                <div class="error">• <?= htmlspecialchars($e) ?></div>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if (isset($success) && $success !== ''): ?>
            <div class="success"><?= htmlspecialchars($success) ?></div>
        <?php endif; ?>
    </div>

    <section class="hero">
        <h1>How To Order Online?</h1>
        <img src="tomato_spaghetti.webp" alt="Pasta Dish">
    </section>

    <section class="step-bar">
        <div class="step"><div class="step-number">1</div><div class="step-text">Sign in / Login</div></div>
        <div class="step"><div class="step-number">2</div><div class="step-text">Place Order</div></div>
        <div class="step"><div class="step-number">3</div><div class="step-text">Delivery / Pickup</div></div>
    </section>

    <section class="menu-btn-wrapper">
        <a href="menu.php">
            <button class="menu-btn" type="button">Menu</button>
        </a>
    </section>


    <section class="order-table-section">
        <h3>🍽 Buon Appetito!<br><br>
        Check your meals, update quantities, and enjoy your Italian feast.</h3>

        <form method="post">
            <input type="hidden" name="action" value="update">
            <table>
            <table>
                <tr>
                    <th>Item</th>
                    <th>Quantity</th>
                    <th>Price (Rs)</th>
                </tr>

                <?php foreach ($menu as $m): ?>
                    <?php
                        $id = $m['item_id'];
                        $qty = $_SESSION['cart'][$id] ?? 0; // pre-fill existing quantity
                    ?>
                    <tr>
                        <td><?= htmlspecialchars($m['item_name']) ?></td>

                        <td><input type="number" name="qty[<?= $id ?>]" value="<?= $qty ?>" min="0"></td>

                        <td><?= number_format($m['price'], 2) ?></td>
                    </tr>
                <?php endforeach; ?>
            </table>

          <button class="cart-btn" type="submit">Update Cart</button>

        </form>

        <div class="total-amount">Total Amount: Rs <?= number_format($total_display, 2) ?></div>
    </section>

    <section class="delivery-strip">
 
            <form method="post">
                <button class="delivery-btn" type="button">Delivery / Pick Up</button>

                <div class="delivery-form">
                    <label><input type="radio" name="method" value="delivery"> Delivery</label>
                    <label><input type="radio" name="method" value="pickup"> Pickup</label>
                    <br><br>
                    <label>Address:
                        <input type="text" name="address" placeholder="Required only for Delivery">
                    </label>

                    <input type="hidden" name="action" value="checkout">

                    <input type="hidden" name="total" value="<?= $total_display ?>">
                    <br><br>
                    <button type="submit">Confirm Order</button>
                </div>
            </form>
  
    </section>



    <section class="row">
        <img src="parmessan_spagetti.jpg" alt="">
        <img src="lemonade.png" alt="">
        <img src="spaghetti_basilico1.jpg" alt="">
    </section>
</main>

<footer>
    <div class="footer-logo-strip">
        <img src="red_basilico.jpeg" alt="">
    </div>

    <div class="footer-content">
        <div>
            <div class="footer-title">Doormat Navigation</div>
            <ul class="footer-list">
                <li>Home</li><li>About</li><li>Menu</li>
                <li>Reservation</li><li>Order Online</li>
                <li>Registration</li><li>Login</li>
            </ul>
        </div>

        <div>
            <div class="footer-title">Contact</div>
            <p class="footer-small">
                Port Louis, Mauritius<br>
                +230 5555 1234<br>
                contact@basilico.mu
            </p>
        </div>

        <div>
            <div class="footer-title">Opening Hours</div>
            <p class="footer-small">
                Mon–Fri: 11 AM – 10 PM<br><br>
                Sat–Sun: 12 PM – 11:30 PM
            </p>
        </div>
    </div>
</footer>

</body>
</html>